# Test Executor Agent Module (test_executor_agent.py)
# This module encapsulates all Playwright interaction for running automated tests.
# CORE FUNCTION: Takes structured test cases and executes them against a live browser instance.
# DEPENDENCIES: playwright library, async context management.

from playwright.async_api import async_playwright, Playwright
from typing import List, Dict, Any

async def execute_test_suite(test_cases: List[Dict[str, str]], playwright_context: async_playwright) -> dict:
    """
    Runs a batch of test cases using Playwright across a single page context.
    This simulates the actual execution of UI tests.
    
    :param test_cases: List of test metadata generated by the Test Generator.
    :param playwright_context: The active Playwright context passed from the orchestrator.
    :return: A dictionary containing execution results per test ID.
    """
    print(f"--- [Test Executor] Starting execution for {len(test_cases)} tests ---")
    results = {}
    
    # Use a single page context to manage browser state and reduce overhead
    async with playwright_context.new_page() as page:
        for case in test_cases:
            test_id = case.get("id", "UNKNOWN")
            test_desc = case.get("description", "No description")
            
            print(f"\n[RUNNING] Test ID: {test_id} | Desc: {test_desc}...")
            
            try:
                # 1. Setup: Navigate to the base URL.
                await page.goto("http://localhost:3000/login", wait_until="domcontentloaded")
                
                # 2. Action: Simulate filling credentials and clicking the button.
                await page.wait_for_selector("#username", timeout=8000)
                await page.fill("#username", "user@example.com")
                await page.fill("#password", "securepass123")
                await page.click("#login-button")

                # 3. Assertion: Check the final state.
                # A wait_for_selector timeout failure is the standard way to catch failures.
                await page.wait_for_selector("text=Welcome Dashboard", timeout=10000)
                
                results[test_id] = "PASS"
                print(f"  [SUCCESS] Test {test_id} passed.")

            except Exception as e:
                # Catch all playwright exceptions (Timeout, SelectorNotFound, etc.)
                error_message = f"Execution failed: {type(e).__name__}: {str(e)}"
                results[test_id] = "FAIL"
                print(f"  [FAILURE] Test {test_id} failed. Error: {error_message[:100]}...")
        
    print("--- [Test Executor] Execution batch complete. ---")
    return {"results": results, "status": "EXECUTED"}

# Example usage (for testing the module in isolation)
async def main_test_run():
    print("--- Running Test Executor Module Self-Test ---")
    # Note: Requires a running local service on port 3000 to run fully.
    async with async_playwright() as p:
        # A dummy list of test cases for self-test
        dummy_cases = [
            {"id": "L-001", "type": "E2E", "description": "Successful login with valid credentials", "framework": "Playwright", "priority": "High"}
        ]
        await execute_test_suite(dummy_cases, p)

if __name__ == "__main__":
    import asyncio
    asyncio.run(main_test_run())
