import subprocess
import os
from typing import List, Dict, Any
from .protocol import generate_playwright_test # Assuming a utility function exists

def run_playwright_tests(test_files: List[str], playwright_executable_path: str) -> Dict[str, Any]:
    """
    Executes a batch of Playwright test files using subprocess.
    Captures standard output and return codes.
    """
    print(f"Executing {len(test_files)} test file(s) using Playwright...")
    
    # Construct the command: npx playwright test --workers=1 --project=chromium test_file1.spec.ts test_file2.spec.ts ...
    command = ["npx", "playwright", "test", "--workers=1", "--project=chromium"] + test_files
    
    try:
        # Use subprocess.run to capture synchronous execution output
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            check=False # Do not raise exception on non-zero exit code
        )
        
        report = {
            "status_code": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "success": result.returncode == 0
        }
        return report
    except FileNotFoundError:
        return {"error": "Playwright executable or node command not found. Ensure dependencies are installed.", "success": False}
    except Exception as e:
        return {"error": f"An unexpected error occurred during execution: {e}", "success": False}

def process_test_execution(generated_test_files: List[str]) -> str:
    """
    Main execution function. Takes generated test file list and runs the executor.
    Returns a formatted report string.
    """
    if not generated_test_files:
        return "No test files provided to the Test Executor Agent."

    # 1. Run tests
    execution_report = run_playwright_tests(generated_test_files, "npx")
    
    # 2. Generate structured report based on results
    if execution_report.get("success"):
        summary = "✅ SUCCESS: All tests passed successfully."
    else:
        summary = f"❌ FAILURE: Tests failed. Exit Code: {execution_report['status_code']}"

    final_report = f"""
# Test Execution Report
**Overall Status:** {summary}

## Raw Output Analysis
**STDOUT:**
{execution_report.get('stdout', 'No STDOUT captured.')}

**STDERR (Errors/Warnings):**
{execution_report.get('stderr', 'No STDERR captured.')}

---
*This report was generated by the Test Executor Agent.*
"""
    return final_report

# Example usage:
if __name__ == "__main__":
    # This list must be populated by the Test Generator Agent's orchestrator
    mock_test_files = [
        "harness/test_output/mock_user_auth.spec.ts", 
        "harness/test_output/mock_checkout.spec.ts"
    ]
    report = process_test_execution(mock_test_files)
    print("\n===============================================")
    print("FINAL TEST EXECUTION SUMMARY")
    print("===============================================")
    print(report)
